using System.Reflection;

namespace DaisyBlazor.Components.Tests;

/// <summary>
/// Guards the generated Material Symbols catalogue (<c>Compat/Icons.cs</c>).
/// </summary>
/// <remarks>
/// The catalogue is generated by <c>scripts/generate-icons.py</c> from the official codepoints
/// list. Downstream code compiles against <c>Icons.Material.Filled.X</c>, so regeneration must
/// never rename a constant (a build break) and must never <i>repoint</i> one (far worse — the
/// glyph changes with no error anywhere). These are the 133 Filled and 2 Outlined
/// constants that existed before the catalogue was generated; every one must survive verbatim.
/// </remarks>
public class IconCatalogueTests
{
    private static readonly (string Name, string Value)[] LegacyFilled =
    [
        ("AcUnit", "ac_unit"),
        ("AccessTime", "access_time"),
        ("Accessible", "accessible"),
        ("Add", "add"),
        ("AdminPanelSettings", "admin_panel_settings"),
        ("Air", "air"),
        ("AirlineSeatReclineNormal", "airline_seat_recline_normal"),
        ("AirplaneTicket", "airplane_ticket"),
        ("AirplanemodeActive", "airplanemode_active"),
        ("AirportShuttle", "airport_shuttle"),
        ("Analytics", "analytics"),
        ("Apps", "apps"),
        ("ArrowBack", "arrow_back"),
        ("ArrowDropDown", "arrow_drop_down"),
        ("ArrowForward", "arrow_forward"),
        ("ArrowRight", "arrow_right"),
        ("ArrowRightAlt", "arrow_right_alt"),
        ("Assessment", "assessment"),
        ("Assignment", "assignment"),
        ("Badge", "badge"),
        ("Balance", "balance"),
        ("BarChart", "bar_chart"),
        ("Block", "block"),
        ("BubbleChart", "bubble_chart"),
        ("Build", "build"),
        ("Business", "business"),
        ("CalendarMonth", "calendar_month"),
        ("CalendarToday", "calendar_today"),
        ("Cancel", "cancel"),
        ("Check", "check"),
        ("CheckCircle", "check_circle"),
        ("CheckCircleOutline", "check_circle"),
        ("ChevronLeft", "chevron_left"),
        ("ChevronRight", "chevron_right"),
        ("Clear", "clear"),
        ("Close", "close"),
        ("Cloud", "cloud"),
        ("CloudOff", "cloud_off"),
        ("CloudUpload", "cloud_upload"),
        ("Computer", "computer"),
        ("ConfirmationNumber", "confirmation_number"),
        ("ContentCopy", "content_copy"),
        ("DarkMode", "dark_mode"),
        ("Dashboard", "dashboard"),
        ("DateRange", "date_range"),
        ("Delete", "delete"),
        ("DesktopWindows", "desktop_windows"),
        ("DevicesOther", "devices_other"),
        ("DoneAll", "done_all"),
        ("DoorFront", "door_front"),
        ("Download", "download"),
        ("Drafts", "drafts"),
        ("Edit", "edit"),
        ("Email", "email"),
        ("Error", "error"),
        ("FileDownload", "file_download"),
        ("FilterAltOff", "filter_alt_off"),
        ("FilterList", "filter_list"),
        ("FlashOn", "flash_on"),
        ("Flight", "flight"),
        ("FlightLand", "flight_land"),
        ("FlightTakeoff", "flight_takeoff"),
        ("Grain", "grain"),
        ("GridOn", "grid_on"),
        ("Help", "help"),
        ("History", "history"),
        ("Home", "home"),
        ("Hub", "hub"),
        ("Info", "info"),
        ("InsertChart", "insert_chart"),
        ("LightMode", "light_mode"),
        ("List", "list"),
        ("LocalGasStation", "local_gas_station"),
        ("LocalParking", "local_parking"),
        ("LocalShipping", "local_shipping"),
        ("LocationOn", "location_on"),
        ("Lock", "lock"),
        ("Login", "login"),
        ("Logout", "logout"),
        ("MeetingRoom", "meeting_room"),
        ("Menu", "menu"),
        ("MenuBook", "menu_book"),
        ("Navigation", "navigation"),
        ("Notes", "notes"),
        ("Notifications", "notifications"),
        ("NotificationsActive", "notifications_active"),
        ("OpenInNew", "open_in_new"),
        ("Palette", "palette"),
        ("People", "people"),
        ("PeopleAlt", "people_alt"),
        ("Person", "person"),
        ("PersonAdd", "person_add"),
        ("PictureAsPdf", "picture_as_pdf"),
        ("PlaylistAdd", "playlist_add"),
        ("Preview", "preview"),
        ("Print", "print"),
        ("Public", "public"),
        ("QrCode", "qr_code"),
        ("QuestionMark", "question_mark"),
        ("Radar", "radar"),
        ("Refresh", "refresh"),
        ("Save", "save"),
        ("Schedule", "schedule"),
        ("School", "school"),
        ("Search", "search"),
        ("SearchOff", "search_off"),
        ("Security", "security"),
        ("Settings", "settings"),
        ("SettingsBrightness", "settings_brightness"),
        ("Shield", "shield"),
        ("Snooze", "snooze"),
        ("Speed", "speed"),
        ("SupportAgent", "support_agent"),
        ("TableChart", "table_chart"),
        ("Tag", "tag"),
        ("Thunderstorm", "thunderstorm"),
        ("Timeline", "timeline"),
        ("Timer", "timer"),
        ("TravelExplore", "travel_explore"),
        ("TrendingUp", "trending_up"),
        ("Tune", "tune"),
        ("Tv", "tv"),
        ("Umbrella", "umbrella"),
        ("VerifiedUser", "verified_user"),
        ("ViewDay", "view_day"),
        ("ViewList", "view_list"),
        ("ViewWeek", "view_week"),
        ("Visibility", "visibility"),
        ("Warning", "warning"),
        ("WbCloudy", "wb_cloudy"),
        ("WbSunny", "wb_sunny"),
        ("WbTwilight", "wb_twilight"),
        ("Weekend", "weekend"),
    ];

    private static readonly (string Name, string Value)[] LegacyOutlined =
    [
        ("Error", "error"),
        ("NotificationsNone", "notifications_none"),
    ];

    private static IReadOnlyDictionary<string, string> Constants(Type type) =>
        type.GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy)
            .Where(f => f is { IsLiteral: true, IsInitOnly: false } && f.FieldType == typeof(string))
            .ToDictionary(f => f.Name, f => (string)f.GetRawConstantValue()!);

    [Fact]
    public void Every_pre_generation_Filled_constant_survives_with_the_same_value()
    {
        IReadOnlyDictionary<string, string> actual = Constants(typeof(Icons.Material.Filled));

        foreach ((string name, string value) in LegacyFilled)
        {
            actual.ShouldContainKey(name, $"constant {name} disappeared — that is a source-breaking change downstream");
            actual[name].ShouldBe(value, $"constant {name} was repointed; the rendered glyph would change silently");
        }
    }

    [Fact]
    public void Every_pre_generation_Outlined_constant_survives_with_the_same_value()
    {
        IReadOnlyDictionary<string, string> actual = Constants(typeof(Icons.Material.Outlined));

        foreach ((string name, string value) in LegacyOutlined)
        {
            actual.ShouldContainKey(name);
            actual[name].ShouldBe(value);
        }
    }

    [Fact]
    public void CheckCircleOutline_still_maps_to_check_circle()
    {
        // The one real collision: `check_circle_outline` is a legacy Material *Icons* ligature
        // whose PascalCase collides with this MudBlazor-compat alias. Consumers load the Material
        // Symbols *Outlined* font, where "check_circle" already renders outlined — so the alias
        // must keep winning, and the legacy ligature must stay dropped.
        Icons.Material.Filled.CheckCircleOutline.ShouldBe("check_circle");
    }

    [Fact]
    public void Catalogue_covers_the_full_symbol_set_not_a_curated_subset()
    {
        // The bug this fixes: a 135-entry hand-curated catalogue meant any icon outside it
        // failed to compile. Guard against silently regressing to a subset.
        Constants(typeof(Icons.Material.Filled)).Count.ShouldBeGreaterThan(4000);
    }

    [Fact]
    public void Digit_leading_ligatures_get_a_legal_identifier()
    {
        Icons.Material.Filled._10k.ShouldBe("10k");
    }
}
