#!/usr/bin/env python3
"""Regenerate Compat/Icons.cs from the official Material Symbols codepoints list.

    python3 scripts/generate-icons.py [path/to/*.codepoints]

With no argument the list is downloaded from google/material-design-icons.

Why this is generated
---------------------
The catalogue used to be a hand-curated subset (135 entries, sized exactly to one
downstream app's usage), so reaching for any icon outside it broke the build with
CS0117 — a papercut hit repeatedly in practice.

Two invariants this script enforces, because breaking either is silent:

1. **Every previously-published constant keeps its exact name AND value.** Downstream
   code compiles against `Icons.Material.Filled.X`; a rename is a build break and a
   *repoint* is worse — the glyph changes with no error anywhere. Existing entries
   therefore always win over generated ones, and the script aborts if that fails.

   Concrete case: `check_circle_outline` is a legacy Material *Icons* ligature whose
   PascalCase collides with the compat alias `CheckCircleOutline = "check_circle"`.
   Consumers load the **Material Symbols Outlined** font, where `check_circle` already
   renders outlined — so the existing mapping is correct and the legacy ligature is
   dropped rather than allowed to steal the name.

2. **`Material.Outlined` is left alone.** Material Symbols expresses fill as a font axis
   (FILL), not as separate ligatures, so `Outlined.Error` and `Filled.Error` are both
   "error". That namespace is a MudBlazor-compat shim; regenerating 4k constants into it
   would double the assembly metadata for zero behavioural gain.
"""
import re
import subprocess
import sys
import pathlib
import collections

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICONS = ROOT / "src/DaisyBlazor.Components/Compat/Icons.cs"
URL = ("https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/"
       "MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints")


def load_codepoints() -> list[str]:
    if len(sys.argv) > 1:
        text = pathlib.Path(sys.argv[1]).read_text()
    else:
        text = subprocess.run(["curl", "-sfL", "--max-time", "60", URL],
                              capture_output=True, text=True, check=True).stdout
    return sorted({line.split()[0] for line in text.splitlines() if line.strip()})


def pascal(ligature: str) -> str:
    name = "".join(part.capitalize() for part in ligature.split("_"))
    # C# identifiers cannot start with a digit ("10k" -> "_10k").
    return "_" + name if name[:1].isdigit() else name


def parse_class(source: str, class_name: str) -> dict[str, str]:
    match = re.search(rf"public static class {class_name}\s*\{{(.*?)\n        \}}", source, re.S)
    if not match:
        raise SystemExit(f"could not locate class {class_name} in {ICONS}")
    return dict(re.findall(r'public const string (\w+) = "([^"]+)";', match.group(1)))


def main() -> None:
    source = ICONS.read_text()
    existing_filled = parse_class(source, "Filled")
    outlined = parse_class(source, "Outlined")

    ligatures = load_codepoints()
    generated: dict[str, str] = {}
    collisions: dict[str, list[str]] = collections.defaultdict(list)
    for ligature in ligatures:
        name = pascal(ligature)
        if name in generated and generated[name] != ligature:
            collisions[name].append(ligature)
            continue
        generated[name] = ligature

    # Invariant 1: existing always wins.
    shadowed = {n: (existing_filled[n], generated[n])
                for n in existing_filled
                if n in generated and generated[n] != existing_filled[n]}
    for name in shadowed:
        generated[name] = existing_filled[name]

    merged = dict(sorted({**generated, **existing_filled}.items()))

    broken = {n: (v, merged.get(n)) for n, v in existing_filled.items() if merged.get(n) != v}
    if broken:
        raise SystemExit(f"refusing to generate: existing constants would change -> {broken}")

    lines = [
        "// <auto-generated>",
        "//     Material Symbols ligature catalogue.",
        "//     Regenerate with: python3 scripts/generate-icons.py",
        "//     Source: https://github.com/google/material-design-icons (variablefont/*.codepoints)",
        "//     Do not edit by hand — see the script for the invariants it enforces.",
        "// </auto-generated>",
        "",
        "namespace DaisyBlazor;",
        "",
        "/// <summary>",
        "/// Material Symbols ligature names for <see cref=\"Icon\"/>'s <c>Name</c> parameter.",
        "/// </summary>",
        "/// <remarks>",
        "/// <para>",
        "/// These are plain ligature strings — <c>Icons.Material.Filled.Map</c> is literally",
        "/// <c>\"map\"</c>. The constants exist for discoverability and compile-time safety;",
        "/// <c>&lt;Icon Name=\"map\" /&gt;</c> is equally valid and always was.",
        "/// </para>",
        "/// <para>",
        "/// The catalogue covers the full Material Symbols set. It was previously a hand-curated",
        "/// subset, so any icon outside it failed to compile.",
        "/// </para>",
        "/// </remarks>",
        "public static class Icons",
        "{",
        "    /// <summary>Material Design icon families.</summary>",
        "    public static class Material",
        "    {",
        "        /// <summary>Material Symbols ligatures.</summary>",
        "        public static class Filled",
        "        {",
    ]
    lines += [f'            public const string {name} = "{lig}";' for name, lig in merged.items()]
    lines += [
        "        }",
        "",
        "        /// <summary>",
        "        /// MudBlazor-compat aliases. Material Symbols expresses fill as a font axis (FILL),",
        "        /// not as separate ligatures, so these resolve to the same glyphs as",
        "        /// <see cref=\"Filled\"/> — this namespace exists only so migrated code keeps",
        "        /// compiling, and is deliberately not regenerated.",
        "        /// </summary>",
        "        public static class Outlined",
        "        {",
    ]
    lines += [f'            public const string {name} = "{lig}";' for name, lig in sorted(outlined.items())]
    lines += ["        }", "    }", "}", ""]

    ICONS.write_text("\n".join(lines))

    print(f"ligatures                   : {len(ligatures)}")
    print(f"collisions dropped          : {sum(len(v) for v in collisions.values())} {dict(collisions)}")
    print(f"existing kept over generated: {len(shadowed)} {shadowed}")
    print(f"Filled constants            : {len(merged)}  (was {len(existing_filled)})")
    print(f"Outlined constants          : {len(outlined)} (preserved verbatim)")


if __name__ == "__main__":
    main()
